version: '3.8'

services:
  web:
    image: deusgaudio/employees_api:main
    command: python3 app/main.py
    ports:
      - 8090:8090
    depends_on:
      - mongodb
    links:
      - mongodb


  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    command: mongoimport -h mongodb --port=27017 --type=json --file=employees.json --jsonArray


volumes:
  mongodb_data_container: