# This is a basic workflow to help you get started with Actions

name: employy_api_workflow

on: [push]

jobs:
  push_to_docker_hub:
    runs-on: ubuntu-latest
    name: Push Docker image to Docker Hub
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: deusgaudio/employees_api:v1
          tag_with_ref: true
  
