# This is a basic workflow to help you get started with Actions

name: employee_api_workflow

on: [push]

jobs:  

  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        
    - name: Lint with flake8
      run: flake8 .
  
  push_to_docker_hub:
    runs-on: ubuntu-latest
    name: Push Docker image to Docker Hub
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: deusgaudio/employees_api
          tag_with_ref: true
  
